local query = get("query");
local items = get("item-name", true);

-- Titles generated with ChatGPT
local titles = {
    "Shucking Sensations: Corn Unwrapped",
    "Cob Confidential: Secrets of the Kernel",
    "Popping Pleasure: Popcorn Perfection",
    "Golden Grains: A-Maize-ing Adventures",
    "Cornography Classics: Vintage Vines",
    "Silky Smooth: The Art of Husk Removal",
    "Kernel Knowledge: Corn Facts You Didn't Know",
    "Sizzling Cobs: BBQ Corn on the Cob",
    "Corny Comedy: Jokes from the Field",
    "Ear-resistible: Sweet Corn Delights",
    "Popcorn Paradise: From Kernel to Pop",
    "Stalk and Awe: Giant Corn Plants",
    "Corn Fiesta: Street Food Specialties",
    "Cornucopia Chronicles: Harvest Tales",
    "Husky Encounters: Cornfield Capers",
    "Cobbin' it Up: Corn Party Extravaganza",
    "Naughty by Nature: Cornfield Antics",
    "Sweet and Steamy: Corn on the Cob Cooking Tips",
    "Unleashed: The Great Corn Hunt",
    "Field of Dreams: Corn Maze Adventures",
    "Cobbing Together: DIY Corn Crafts",
    "Saucy Shucks: Corn Recipes with a Twist",
    "Corny Couples: Matching Cobs",
    "Grainy Goodness: Homemade Cornmeal Treats",
    "Cob Crackers: Corn Snacks Uncovered",
    "Shuckfest: Epic Corn Shucking Competitions",
    "The Kernel Chronicles: Corn Myths and Legends",
    "Popped Perfection: Gourmet Popcorn Creations",
    "Ear-tastic: Unique Corn Varieties Explained",
    "Cobbler's Delight: Corn Desserts You Must Try",
    "Corn-fed: Farm-to-Table Corn Delicacies",
    "Cob Confidential: Behind the Stalk",
    "Mighty Maize: Corn's Role in History",
    "Steamy Ears: Corn Steaming Techniques",
    "The Shuck Stops Here: Ultimate Corn Shucking Guide",
    "Cornfield Capers: Mischief in the Maize",
    "Popcorn Prowess: Secrets to Perfect Pops",
    "Harvest Hustle: Corn Picking Frenzy",
    "Husk Hustlers: Cornfield Shenanigans",
    "Golden Ears: Gourmet Corn Recipes",
    "Kernel Kings: Corn Growing Tips",
    "Corn Crusaders: Saving the Crop",
    "Stalk Stories: Tales from the Field",
    "Husker Hijinks: Fun with Corn Husks",
    "Mighty Munchies: Corn Snack Ideas",
    "Popping Perfection: The Best Popcorn Toppings",
    "Corn-tastic: Amazing Corn Facts",
    "Sweet Kernel: Corn Syrup Creations",
    "Cobbing Class: How to Grow Corn",
    "Grill Masters: Corn on the BBQ",
    "Field Frolics: Corn Maze Challenges",
    "Shuck and Awe: Corn Harvest Techniques",
    "Ear Envy: Unique Corn Cob Shapes",
    "Popcorn Party: Flavored Popcorn Recipes",
    "Corny Creations: Corn Art and Crafts",
    "Cob Connoisseur: Tasting Different Corn Varieties",
    "Golden Harvest: Cornfield Journeys",
    "Cornfield Comedy: Hilarious Corn Jokes",
    "Kernel Keepers: Storing Corn Long-Term",
    "Corn Cuisine: Gourmet Dishes with Corn",
    "Cob Creations: Corn DIY Projects",
    "Silky Secrets: Corn Silk Uses",
    "Shuck Stars: Corn Shucking Tips",
    "Stalk Talk: Corn Growing Tips",
    "Popcorn Pizzazz: Creative Popcorn Ideas",
    "Harvest Heroes: Stories from the Cornfield",
    "Cob Crafters: Handmade Corn Products",
    "Corn Carnival: Fun Corn Games",
    "Kernel Kraziness: Fun Corn Facts",
    "Pop and Lock: The Best Popcorn Machines",
    "Sweet Corn Serenade: Corn Recipe Specials",
    "Cobblers' Delight: Cornbread and More",
    "Cornfield Chronicles: Farming Adventures",
    "Kernel Quest: Finding Rare Corn Varieties",
    "Cob Capers: Fun in the Field",
    "Golden Grain: Corn's Role in Cuisine",
    "Shuck Shack: Corn Recipe Headquarters",
    "Corn Comedy Hour: Jokes and Stories",
    "Kernel Craze: Popular Corn Snacks",
    "Popcorn Perfection: Tips for the Perfect Pop",
    "Stalk Sagas: Cornfield Tales",
    "Sweet and Savory: Corn Recipes Galore",
    "Cob Collectors: Rare Corn Varieties",
    "Silky Smooth: Corn Silk Uses",
    "Grill and Thrill: BBQ Corn Recipes",
    "Harvest Hilarity: Funny Corn Stories",
    "Ear Excellence: Perfect Corn Cooking",
    "Popcorn Pals: Popcorn Pairings",
    "Corn Charm: Corn-Based Decorations",
    "Kernel Craftsmanship: DIY Corn Projects",
    "Cob Kisses: Sweet Corn Recipes",
    "Cornfield Confidential: Behind the Scenes",
    "Golden Grains: Corn's Impact on History",
    "Popcorn Party: Movie Night Specials",
    "Cob Creations: Artistic Uses for Corn",
    "Stalk Strategies: Corn Growing Techniques",
    "Corn Cuisine: Global Corn Recipes",
    "Shuck Stars: Mastering Corn Shucking",
    "Harvest Hustle: Corn Picking Fun",
    "Kernel Kisses: Corn Recipe Secrets",
    "Popcorn Perks: Healthy Popcorn Ideas",
    "Cob Comedians: Funny Corn Stories",
    "Cornfield Camaraderie: Farmer Stories",
    "Golden Gourmet: Fancy Corn Dishes",
    "Shuck and Jive: Corn Harvest Fun"
};

for index, item in ipairs(items) do
    item.set_content(titles[math.random(#titles)]);
end
